export const GET_ARMADAS_REQUEST = 'GET_ARMADAS_REQUEST';
export const GET_ARMADAS_SUCCESS = 'GET_ARMADAS_SUCCESS';
export const GET_ARMADAS_FAIL = 'GET_ARMADAS_FAIL';

export const GET_ARMADA_REQUEST = 'GET_ARMADA_REQUEST';
export const GET_ARMADA_SUCCESS = 'GET_ARMADA_SUCCESS';
export const GET_ARMADA_FAIL = 'GET_ARMADA_FAIL';

export const ADD_ARMADA_REQUEST = 'ADD_ARMADA_REQUEST';
export const ADD_ARMADA_SUCCESS = 'ADD_ARMADA_SUCCESS';
export const ADD_ARMADA_FAIL = 'ADD_ARMADA_FAIL';

export const UPDATE_ARMADA_REQUEST = 'UPDATE_ARMADA_REQUEST';
export const UPDATE_ARMADA_SUCCESS = 'UDPATE_ARMADA_SUCCESS';
export const UPDATE_ARMADA_FAIL = 'UPDATE_ARMADA_FAIL';

export const DELETE_ARMADA_REQUEST = 'DELETE_ARMADA_REQUEST';
export const DELETE_ARMADA_SUCCESS = 'DELETE_ARMADA_SUCCESS';
export const DELETE_ARMADA_FAIL = 'DELETE_ARMADA_FAIL';

export const RESET_ARMADA = 'RESET_ARMADA';
