export const GET_CABANGS_REQUEST = 'GET_CABANGS_REQUEST';
export const GET_CABANGS_SUCCESS = 'GET_CABANGS_SUCCESS';
export const GET_CABANGS_FAIL = 'GET_CABANGS_FAIL';

export const GET_CABANG_REQUEST = 'GET_CABANG_REQUEST';
export const GET_CABANG_SUCCESS = 'GET_CABANG_SUCCESS';
export const GET_CABANG_FAIL = 'GET_CABANG_FAIL';

export const ADD_CABANG_REQUEST = 'ADD_CABANG_REQUEST';
export const ADD_CABANG_SUCCESS = 'ADD_CABANG_SUCCESS';
export const ADD_CABANG_FAIL = 'ADD_CABANG_FAIL';

export const UPDATE_CABANG_REQUEST = 'UPDATE_CABANG_REQUEST';
export const UPDATE_CABANG_SUCCESS = 'UDPATE_CABANG_SUCCESS';
export const UPDATE_CABANG_FAIL = 'UPDATE_CABANG_FAIL';

export const DELETE_CABANG_REQUEST = 'DELETE_CABANG_REQUEST';
export const DELETE_CABANG_SUCCESS = 'DELETE_CABANG_SUCCESS';
export const DELETE_CABANG_FAIL = 'DELETE_CABANG_FAIL';

export const RESET_CABANG = 'RESET_CABANG';
