export const GET_COVERAGEAREAS_REQUEST = 'GET_COVERAGEAREAS_REQUEST';
export const GET_COVERAGEAREAS_SUCCESS = 'GET_COVERAGEAREAS_SUCCESS';
export const GET_COVERAGEAREAS_FAIL = 'GET_COVERAGEAREAS_FAIL';

export const GET_COVERAGEAREA_REQUEST = 'GET_COVERAGEAREA_REQUEST';
export const GET_COVERAGEAREA_SUCCESS = 'GET_COVERAGEAREA_SUCCESS';
export const GET_COVERAGEAREA_FAIL = 'GET_COVERAGEAREA_FAIL';

export const ADD_COVERAGEAREA_REQUEST = 'ADD_COVERAGEAREA_REQUEST';
export const ADD_COVERAGEAREA_SUCCESS = 'ADD_COVERAGEAREA_SUCCESS';
export const ADD_COVERAGEAREA_FAIL = 'ADD_COVERAGEAREA_FAIL';

export const UPDATE_COVERAGEAREA_REQUEST = 'UPDATE_COVERAGEAREA_REQUEST';
export const UPDATE_COVERAGEAREA_SUCCESS = 'UDPATE_COVERAGEAREA_SUCCESS';
export const UPDATE_COVERAGEAREA_FAIL = 'UPDATE_COVERAGEAREA_FAIL';

export const DELETE_COVERAGEAREA_REQUEST = 'DELETE_COVERAGEAREA_REQUEST';
export const DELETE_COVERAGEAREA_SUCCESS = 'DELETE_COVERAGEAREA_SUCCESS';
export const DELETE_COVERAGEAREA_FAIL = 'DELETE_COVERAGEAREA_FAIL';

export const RESET_COVERAGEAREA = 'RESET_COVERAGEAREA';
