export const GET_GRUPMENUS_REQUEST = 'GET_GRUPMENUS_REQUEST';
export const GET_GRUPMENUS_SUCCESS = 'GET_GRUPMENUS_SUCCESS';
export const GET_GRUPMENUS_FAIL = 'GET_GRUPMENUS_FAIL';

export const GET_GRUPMENU_REQUEST = 'GET_GRUPMENU_REQUEST';
export const GET_GRUPMENU_SUCCESS = 'GET_GRUPMENU_SUCCESS';
export const GET_GRUPMENU_FAIL = 'GET_GRUPMENU_FAIL';

export const ADD_GRUPMENU_REQUEST = 'ADD_GRUPMENU_REQUEST';
export const ADD_GRUPMENU_SUCCESS = 'ADD_GRUPMENU_SUCCESS';
export const ADD_GRUPMENU_FAIL = 'ADD_GRUPMENU_FAIL';

export const UPDATE_GRUPMENU_REQUEST = 'UPDATE_GRUPMENU_REQUEST';
export const UPDATE_GRUPMENU_SUCCESS = 'UDPATE_GRUPMENU_SUCCESS';
export const UPDATE_GRUPMENU_FAIL = 'UPDATE_GRUPMENU_FAIL';

export const DELETE_GRUPMENU_REQUEST = 'DELETE_GRUPMENU_REQUEST';
export const DELETE_GRUPMENU_SUCCESS = 'DELETE_GRUPMENU_SUCCESS';
export const DELETE_GRUPMENU_FAIL = 'DELETE_GRUPMENU_FAIL';

export const RESET_GRUPMENU = 'RESET_GRUPMENU';
