export const GET_HELPERS_REQUEST = 'GET_HELPERS_REQUEST';
export const GET_HELPERS_SUCCESS = 'GET_HELPERS_SUCCESS';
export const GET_HELPERS_FAIL = 'GET_HELPERS_FAIL';

export const GET_HELPER_REQUEST = 'GET_HELPER_REQUEST';
export const GET_HELPER_SUCCESS = 'GET_HELPER_SUCCESS';
export const GET_HELPER_FAIL = 'GET_HELPER_FAIL';

export const ADD_HELPER_REQUEST = 'ADD_HELPER_REQUEST';
export const ADD_HELPER_SUCCESS = 'ADD_HELPER_SUCCESS';
export const ADD_HELPER_FAIL = 'ADD_HELPER_FAIL';

export const UPDATE_HELPER_REQUEST = 'UPDATE_HELPER_REQUEST';
export const UPDATE_HELPER_SUCCESS = 'UDPATE_HELPER_SUCCESS';
export const UPDATE_HELPER_FAIL = 'UPDATE_HELPER_FAIL';

export const DELETE_HELPER_REQUEST = 'DELETE_HELPER_REQUEST';
export const DELETE_HELPER_SUCCESS = 'DELETE_HELPER_SUCCESS';
export const DELETE_HELPER_FAIL = 'DELETE_HELPER_FAIL';

export const RESET_HELPER = 'RESET_HELPER';
