export const GET_KANTOR_CABANGS_REQUEST = 'GET_KANTOR_CABANGS_REQUEST';
export const GET_KANTOR_CABANGS_SUCCESS = 'GET_KANTOR_CABANGS_SUCCESS';
export const GET_KANTOR_CABANGS_FAIL = 'GET_KANTOR_CABANGS_FAIL';

export const GET_KANTOR_CABANG_REQUEST = 'GET_KANTOR_CABANG_REQUEST';
export const GET_KANTOR_CABANG_SUCCESS = 'GET_KANTOR_CABANG_SUCCESS';
export const GET_KANTOR_CABANG_FAIL = 'GET_KANTOR_CABANG_FAIL';

export const ADD_KANTOR_CABANG_REQUEST = 'ADD_KANTOR_CABANG_REQUEST';
export const ADD_KANTOR_CABANG_SUCCESS = 'ADD_KANTOR_CABANG_SUCCESS';
export const ADD_KANTOR_CABANG_FAIL = 'ADD_KANTOR_CABANG_FAIL';

export const UPDATE_KANTOR_CABANG_REQUEST = 'UPDATE_KANTOR_CABANG_REQUEST';
export const UPDATE_KANTOR_CABANG_SUCCESS = 'UDPATE_KANTOR_CABANG_SUCCESS';
export const UPDATE_KANTOR_CABANG_FAIL = 'UPDATE_KANTOR_CABANG_FAIL';

export const DELETE_KANTOR_CABANG_REQUEST = 'DELETE_KANTOR_CABANG_REQUEST';
export const DELETE_KANTOR_CABANG_SUCCESS = 'DELETE_KANTOR_CABANG_SUCCESS';
export const DELETE_KANTOR_CABANG_FAIL = 'DELETE_KANTOR_CABANG_FAIL';

export const RESET_KANTOR_CABANG = 'RESET_KANTOR_CABANG';
