export const GET_KARYAWANS_REQUEST = 'GET_KARYAWANS_REQUEST';
export const GET_KARYAWANS_SUCCESS = 'GET_KARYAWANS_SUCCESS';
export const GET_KARYAWANS_FAIL = 'GET_KARYAWANS_FAIL';

export const GET_KARYAWAN_REQUEST = 'GET_KARYAWAN_REQUEST';
export const GET_KARYAWAN_SUCCESS = 'GET_KARYAWAN_SUCCESS';
export const GET_KARYAWAN_FAIL = 'GET_KARYAWAN_FAIL';

export const ADD_KARYAWAN_REQUEST = 'ADD_KARYAWAN_REQUEST';
export const ADD_KARYAWAN_SUCCESS = 'ADD_KARYAWAN_SUCCESS';
export const ADD_KARYAWAN_FAIL = 'ADD_KARYAWAN_FAIL';

export const UPDATE_KARYAWAN_REQUEST = 'UPDATE_KARYAWAN_REQUEST';
export const UPDATE_KARYAWAN_SUCCESS = 'UDPATE_KARYAWAN_SUCCESS';
export const UPDATE_KARYAWAN_FAIL = 'UPDATE_KARYAWAN_FAIL';

export const DELETE_KARYAWAN_REQUEST = 'DELETE_KARYAWAN_REQUEST';
export const DELETE_KARYAWAN_SUCCESS = 'DELETE_KARYAWAN_SUCCESS';
export const DELETE_KARYAWAN_FAIL = 'DELETE_KARYAWAN_FAIL';

export const RESET_KARYAWAN = 'RESET_KARYAWAN';
