export const GET_KURIRS_REQUEST = 'GET_KURIRS_REQUEST';
export const GET_KURIRS_SUCCESS = 'GET_KURIRS_SUCCESS';
export const GET_KURIRS_FAIL = 'GET_KURIRS_FAIL';

export const GET_KURIR_REQUEST = 'GET_KURIR_REQUEST';
export const GET_KURIR_SUCCESS = 'GET_KURIR_SUCCESS';
export const GET_KURIR_FAIL = 'GET_KURIR_FAIL';

export const ADD_KURIR_REQUEST = 'ADD_KURIR_REQUEST';
export const ADD_KURIR_SUCCESS = 'ADD_KURIR_SUCCESS';
export const ADD_KURIR_FAIL = 'ADD_KURIR_FAIL';

export const UPDATE_KURIR_REQUEST = 'UPDATE_KURIR_REQUEST';
export const UPDATE_KURIR_SUCCESS = 'UDPATE_KURIR_SUCCESS';
export const UPDATE_KURIR_FAIL = 'UPDATE_KURIR_FAIL';

export const DELETE_KURIR_REQUEST = 'DELETE_KURIR_REQUEST';
export const DELETE_KURIR_SUCCESS = 'DELETE_KURIR_SUCCESS';
export const DELETE_KURIR_FAIL = 'DELETE_KURIR_FAIL';

export const RESET_KURIR = 'RESET_KURIR';
