export const GET_PELANGGANS_REQUEST = 'GET_PELANGGANS_REQUEST';
export const GET_PELANGGANS_SUCCESS = 'GET_PELANGGANS_SUCCESS';
export const GET_PELANGGANS_FAIL = 'GET_PELANGGANS_FAIL';

export const GET_PELANGGAN_REQUEST = 'GET_PELANGGAN_REQUEST';
export const GET_PELANGGAN_SUCCESS = 'GET_PELANGGAN_SUCCESS';
export const GET_PELANGGAN_FAIL = 'GET_PELANGGAN_FAIL';

export const ADD_PELANGGAN_REQUEST = 'ADD_PELANGGAN_REQUEST';
export const ADD_PELANGGAN_SUCCESS = 'ADD_PELANGGAN_SUCCESS';
export const ADD_PELANGGAN_FAIL = 'ADD_PELANGGAN_FAIL';

export const UPDATE_PELANGGAN_REQUEST = 'UPDATE_PELANGGAN_REQUEST';
export const UPDATE_PELANGGAN_SUCCESS = 'UDPATE_PELANGGAN_SUCCESS';
export const UPDATE_PELANGGAN_FAIL = 'UPDATE_PELANGGAN_FAIL';

export const DELETE_PELANGGAN_REQUEST = 'DELETE_PELANGGAN_REQUEST';
export const DELETE_PELANGGAN_SUCCESS = 'DELETE_PELANGGAN_SUCCESS';
export const DELETE_PELANGGAN_FAIL = 'DELETE_PELANGGAN_FAIL';

export const RESET_PELANGGAN = 'RESET_PELANGGAN';
