export const GET_PENGGUNAS_REQUEST = 'GET_PENGGUNAS_REQUEST';
export const GET_PENGGUNAS_SUCCESS = 'GET_PENGGUNAS_SUCCESS';
export const GET_PENGGUNAS_FAIL = 'GET_PENGGUNAS_FAIL';

export const GET_PENGGUNA_REQUEST = 'GET_PENGGUNA_REQUEST';
export const GET_PENGGUNA_SUCCESS = 'GET_PENGGUNA_SUCCESS';
export const GET_PENGGUNA_FAIL = 'GET_PENGGUNA_FAIL';

export const ADD_PENGGUNA_REQUEST = 'ADD_PENGGUNA_REQUEST';
export const ADD_PENGGUNA_SUCCESS = 'ADD_PENGGUNA_SUCCESS';
export const ADD_PENGGUNA_FAIL = 'ADD_PENGGUNA_FAIL';

export const UPDATE_PENGGUNA_REQUEST = 'UPDATE_PENGGUNA_REQUEST';
export const UPDATE_PENGGUNA_SUCCESS = 'UDPATE_PENGGUNA_SUCCESS';
export const UPDATE_PENGGUNA_FAIL = 'UPDATE_PENGGUNA_FAIL';

export const DELETE_PENGGUNA_REQUEST = 'DELETE_PENGGUNA_REQUEST';
export const DELETE_PENGGUNA_SUCCESS = 'DELETE_PENGGUNA_SUCCESS';
export const DELETE_PENGGUNA_FAIL = 'DELETE_PENGGUNA_FAIL';

export const RESET_PENGGUNA = 'RESET_PENGGUNA';
