export const GET_PICFAKTURS_REQUEST = 'GET_PICFAKTURS_REQUEST';
export const GET_PICFAKTURS_SUCCESS = 'GET_PICFAKTURS_SUCCESS';
export const GET_PICFAKTURS_FAIL = 'GET_PICFAKTURS_FAIL';

export const GET_PICFAKTUR_REQUEST = 'GET_PICFAKTUR_REQUEST';
export const GET_PICFAKTUR_SUCCESS = 'GET_PICFAKTUR_SUCCESS';
export const GET_PICFAKTUR_FAIL = 'GET_PICFAKTUR_FAIL';

export const ADD_PICFAKTUR_REQUEST = 'ADD_PICFAKTUR_REQUEST';
export const ADD_PICFAKTUR_SUCCESS = 'ADD_PICFAKTUR_SUCCESS';
export const ADD_PICFAKTUR_FAIL = 'ADD_PICFAKTUR_FAIL';

export const UPDATE_PICFAKTUR_REQUEST = 'UPDATE_PICFAKTUR_REQUEST';
export const UPDATE_PICFAKTUR_SUCCESS = 'UDPATE_PICFAKTUR_SUCCESS';
export const UPDATE_PICFAKTUR_FAIL = 'UPDATE_PICFAKTUR_FAIL';

export const DELETE_PICFAKTUR_REQUEST = 'DELETE_PICFAKTUR_REQUEST';
export const DELETE_PICFAKTUR_SUCCESS = 'DELETE_PICFAKTUR_SUCCESS';
export const DELETE_PICFAKTUR_FAIL = 'DELETE_PICFAKTUR_FAIL';

export const RESET_PICFAKTUR = 'RESET_PICFAKTUR';
