export const GET_VENDORS_REQUEST = 'GET_VENDORS_REQUEST';
export const GET_VENDORS_SUCCESS = 'GET_VENDORS_SUCCESS';
export const GET_VENDORS_FAIL = 'GET_VENDORS_FAIL';

export const GET_VENDOR_REQUEST = 'GET_VENDOR_REQUEST';
export const GET_VENDOR_SUCCESS = 'GET_VENDOR_SUCCESS';
export const GET_VENDOR_FAIL = 'GET_VENDOR_FAIL';

export const ADD_VENDOR_REQUEST = 'ADD_VENDOR_REQUEST';
export const ADD_VENDOR_SUCCESS = 'ADD_VENDOR_SUCCESS';
export const ADD_VENDOR_FAIL = 'ADD_VENDOR_FAIL';

export const UPDATE_VENDOR_REQUEST = 'UPDATE_VENDOR_REQUEST';
export const UPDATE_VENDOR_SUCCESS = 'UDPATE_VENDOR_SUCCESS';
export const UPDATE_VENDOR_FAIL = 'UPDATE_VENDOR_FAIL';

export const DELETE_VENDOR_REQUEST = 'DELETE_VENDOR_REQUEST';
export const DELETE_VENDOR_SUCCESS = 'DELETE_VENDOR_SUCCESS';
export const DELETE_VENDOR_FAIL = 'DELETE_VENDOR_FAIL';

export const RESET_VENDOR = 'RESET_VENDOR';
